#
# @lc app=leetcode id=389 lang=python3
# @lcpr version=30403
#
# [389] Find the Difference
#
# https://leetcode.com/problems/find-the-difference/description/
#
# algorithms
# Easy (60.14%)
# Likes:    5485
# Dislikes: 519
# Total Accepted:    1.1M
# Total Submissions: 1.8M
# Testcase Example:  '"abcd"\n"abcde"\n""\n"y"'
#
# You are given two strings s and t.
# 
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
# 
# Return the letter that was added to t.
# 
# 
# Example 1:
# 
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# 
# 
# Example 2:
# 
# Input: s = "", t = "y"
# Output: "y"
# 
# 
# 
# Constraints:
# 
# 
# 0 <= s.length <= 1000
# t.length == s.length + 1
# s and t consist of lowercase English letters.
# 
# 
#

import sys
import os

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from typing import *
from common.node import *

# @lc code=start
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
    # method 1: sorting
    # time complexity: dominated by the built-in sorted() function.$O(n \log n) + O(n \log n) + O(n)$, which simplifies to $O(n \log n)$.
    # space complexity: O(n), In Python, strings are immutable. When you call sorted(s), Python creates a new list of characters. This requires $O(n)$ additional space to store the characters of string $s$ and $O(n)$ for string $t$.
        # When we call sorted(), both strings are arranged alphabetically and return a list for each character
        s_sorted = sorted(s)
        t_sorted = sorted(t)
        for i in range (len(s)):
            if s_sorted[i] != t_sorted[i]:
                return t_sorted[i]
        # If no mismatch is found in the loop, the extra char is at the en
        return t_sorted[-1]
    # method 2: HashMap
    # time complexity: O(n); space complexity: O(1) (since the alphabet is fixed at 26 chars)
    def findTheDifference(self, s: str, t: str) -> str:
        # 1. Create a frequency map of string s
        count_s = Counter(s)
        # 上面这句可以拆分成下面三句, 但无论是用 Counter(s) 还是用手动 for 循环，它们的复杂度是相同的: 时间复杂度o(n), 空间复杂度o(1): 因为题目限制了只有 26 个小写字母，字典的大小永远不会超过 26，所以是常数级空间。
        # count_s = {}
        # for char in s:
        #     count_s[char] = count_s.get(char, 0) +1
        # 2. Iterate through string t
        for char in t: 
            if count_s[char] == 0:
                return char
            else:
                count_s[char] -= 1
        
# @lc code=end

if __name__ == '__main__':
    solution = Solution()
    # your test code here




#
# @lcpr case=start
# "abcd"\n"abcde"\n
# @lcpr case=end

# @lcpr case=start
# ""\n"y"\n
# @lcpr case=end

#

